# Generated by Django 3.1 on 2020-09-19 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('city', models.CharField(choices=[('Cluj-Napoca', 'Cluj-Napoca'), ('Bucuresti', 'Bucuresti'), ('Timisoara', 'Timisoara'), ('Iasi', 'Iasi'), ('Brasov', 'Brasov'), ('Oradea', 'Oradea'), ('Constanta', 'Constanta'), ('Arad', 'Arad'), ('Sibiu', 'Sibiu'), ('Galati', 'Galati'), ('Pitesti', 'Pitesti'), ('Craiova', 'Craiova'), ('Ploiesti', 'Ploiesti'), ('Baia-Mare', 'Baia-Mare'), ('Targu-Mures', 'Targu-Mures'), ('Buzau', 'Buzau'), ('Braila', 'Braila'), ('Bacau', 'Bacau'), ('Suceava', 'Suceava'), ('Roman', 'Roman'), ('Alba-Iulia', 'Alba-Iulia'), ('Resita', 'Resita'), ('Botosani', 'Botosani'), ('Deva', 'Deva'), ('Mioveni', 'Mioveni'), ('Ramnicu-Valcea', 'Ramnicu-Valcea'), ('Targu-Jiu', 'Targu-Jiu'), ('Drobeta-Turnu Severin', 'Drobeta-Turnu Severin'), ('Targoviste', 'Targoviste'), ('Bistrita', 'Bistrita'), ('Satu-Mare', 'Satu-Mare'), ('Piatra-Neamt', 'Piatra-Neamt'), ('Focsani', 'Focsani'), ('Sebes', 'Sebes')], max_length=800)),
                ('address', models.CharField(max_length=800)),
                ('categories', models.CharField(max_length=800, null=True)),
                ('tazz_page_href', models.URLField(max_length=800, null=True)),
                ('fp_page_href', models.URLField(max_length=800, null=True)),
                ('image', models.URLField(max_length=1000, null=True)),
                ('unique_id', models.CharField(max_length=1000, null=True)),
                ('internal_address', models.CharField(max_length=800)),
                ('street_no', models.CharField(max_length=500, null=True)),
                ('internal_name', models.CharField(max_length=800)),
                ('tazz_delivery_fee', models.CharField(max_length=800, null=True)),
                ('fp_delivery_fee', models.CharField(max_length=800, null=True)),
                ('tazz_minimum_order', models.CharField(max_length=800, null=True)),
                ('fp_minimum_order', models.CharField(max_length=800, null=True)),
                ('restaurant_rating', models.FloatField(null=True)),
                ('reviews_number', models.IntegerField(null=True)),
                ('reviews_total', models.FloatField(blank=True)),
                ('img', models.ImageField(max_length=1000, null=True, upload_to='restaurants/images')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=4000)),
                ('review_date', models.DateField(auto_now_add=True)),
                ('review_rating', models.FloatField(null=True)),
                ('author', models.CharField(max_length=4000, null=True)),
                ('source', models.CharField(choices=[('foodpanda', 'FoodPanda'), ('tazz', 'Tazz')], max_length=4000)),
                ('unique_id', models.CharField(max_length=1000, null=True)),
                ('rest_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
        ),
    ]
