# Generated by Django 3.1 on 2020-09-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200920_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='img',
            field=models.ImageField(max_length=1000, null=True, upload_to='restaurants/images'),
        ),
    ]
