# Generated by Django 3.1 on 2020-09-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20200920_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='search_name',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
