# Generated by Django 3.1 on 2020-09-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_search_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='search_name',
            field=models.CharField(max_length=1200, null=True),
        ),
    ]
